### ISSUE TITLE
calibration

### ISSUE THREAD

**Issue by jasvinder1079** [jremington/ICM_20948-AHRS#8]
after collecting and calibrating using magneto.c ,can i directly use mahony.ino sketch to collect calibrated data(roll pitch and yaw) or need to use these two files (gravity_demo.ino and tilt_compesation.ino) first?
Simply with mahony.ino I'm getting stable roll and pitch as well as yaw ,but yaw values are not accurate.
With relative rotation value ,its showing 10-15 degree less or more .

**Comment by jremington** [comment]
Put the calibration constants for the gyro, magnetometer and accelerometer into the Mahony.ino code and test whether it works as expected.

If the heading is not accurate, the magnetometer calibration constants are not correct.
