### ISSUE TITLE
Magnetometer Calibration

### ISSUE THREAD

**Issue by jasvinder1079** [jremington/ICM_20948-AHRS#9]
While collecting calib data do we need to put sensor in particular direction like x direction of sensor should put in north then rotate sensor in 3D?
and , How often do we need to calibrate this sensor ?Every time when powered up or only during location change?

**Comment by jremington** [comment]
The best overview on magnetometer calculation is this one:  https://thecavepearlproject.org/2015/05/22/calibrating-any-compass-or-accelerometer-for-arduino/

Collect a full 3D sphere of data and calibrate (in place, if possible), when the compass direction for magnetic North is off by more than a couple of degrees.
